# Generated by Django 3.2.23 on 2025-04-06 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compostdata',
            options={'verbose_name_plural': 'Compost Data'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='compostdata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='compostdata',
            name='is_user_donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compostdata',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compostdata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('processed', 'Processed'), ('distributed', 'Distributed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='compostdata',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
